<?php
// PHP code to read directories and determine which files to use
function getJsonFiles($directory)
{
    $files = [];
    if (is_dir($directory)) {
        $handle = opendir($directory);
        if ($handle) {
            while (($file = readdir($handle)) !== false) {
                if (pathinfo($file, PATHINFO_EXTENSION) === 'json') {
                    $files[] = $file;
                }
            }
            closedir($handle);
        }
    }
    return $files;
}

// Check data directory first
$dataFiles = getJsonFiles('./data/');
$useDataDirectory = count($dataFiles) > 0;

if ($useDataDirectory) {
    $directory = 'data';
    $availableFiles = $dataFiles;
} else {
    $directory = 'example';
    $availableFiles = getJsonFiles('./example/');
}
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Homepage</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
            rel="stylesheet"
        />
        <!-- Prism.js for syntax highlighting -->
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-atom-dark.min.css"
            rel="stylesheet"
        />
        <link rel="stylesheet" href="styles.css" />
    </head>
    <body>
        <div id="hero-section">
            <a href="#main-content" id="title-link"><h1 id="page-title"></h1></a>
            <h2 id="page-subtitle"></h2>
            <nav id="menu-container">
                <ul id="navigation-menu"></ul>
            </nav>
        </div>

        <main id="main-content">
            <!-- Dynamic content will be loaded here -->
        </main>

        <!-- PHP-generated configuration for JavaScript -->
        <script>
            // Configuration generated by PHP
            window.homepageConfig = {
                directory: '<?php echo $directory; ?>',
                availableFiles: <?php echo json_encode($availableFiles); ?>
            };
            console.log('PHP detected directory:', window.homepageConfig.directory);
            console.log('Available files:', window.homepageConfig.availableFiles);
        </script>

        <!-- Prism.js JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-core.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/autoloader/prism-autoloader.min.js"></script>
        <script src="script.js"></script>
    </body>
</html>
